"""
Django settings for fit project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
import socket
import dj_database_url
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=edo#v%a+)e_gjkjjxqojk9tnw)*1l%9ebn_rle3vl5z+$e1_j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'fitapp.apps.FitappConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'django_static_fontawesome',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'fit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'tags_extras': 'fitapp.tags_extras',
            }
        },
    },
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': ('%(asctime)s [%(process)d] [%(levelname)s] ' +
                       'pathname=%(pathname)s lineno=%(lineno)s ' +
                       'funcname=%(funcName)s %(message)s'),
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        }
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'testlogger': {
            'handlers': ['console'],
            'level': 'INFO',
        }
    }
}


WSGI_APPLICATION = 'fit.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'entrenamientos',
        'USER': 'cibeles',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)

STATIC_URL = '/static/'

if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads/')

MEDIA_URL = '/uploads/'


OAUTH_CLIENT_ID = '426570479868-h9gncmdlrsgu3is3u8umjcf09h4l6mre.apps.googleusercontent.com'
OAUTH_CLIENT_SECRET = '2-umuj-pyRoyQJn-9rGWLm_O'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'


HOSTNAME = socket.gethostname()
if HOSTNAME == 'CIBELES-1':
    URL_BASE = 'http://127.0.0.1:8000'
    REDIRECT_URI = 'http://127.0.0.1:8000/oauth/login/'
else:
    URL_BASE = 'https://mimifit.herokuapp.com'
    REDIRECT_URI = 'https://mimifit.herokuapp.com/oauth/login/'



CLIENT_ID = "426570479868-h9gncmdlrsgu3is3u8umjcf09h4l6mre.apps.googleusercontent.com"
APP_SECRET_KEY = "2-umuj-pyRoyQJn-9rGWLm_O"

GOOGLEFIT_CONFIG = {
    'CLIENT_ID': "426570479868-h9gncmdlrsgu3is3u8umjcf09h4l6mre.apps.googleusercontent.com",
    'APP_SECRET_KEY': "2-umuj-pyRoyQJn-9rGWLm_O",
    'REDIRECT_URI': REDIRECT_URI,
    'access_token_uri': 'https://accounts.google.com/o/oauth2/token',
    'durationMillis': 86400000,
    'url_aggregate': "https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate",
    'url_session': "https://www.googleapis.com/fitness/v1/users/me/sessions?startTime=%(startTime)s&endTime=%(endTime)s",
    'dataTypeDistanceName': "com.google.distance.delta",
    'dataTypeStepsName':  "com.google.step_count.delta",
    'dataTypeCaloriesName':  "com.google.calories.expended",
    'dataTypeActiveName':  "com.google.active_minutes",
    'dataTypeHeartName': "com.google.heart_minutes",
    'dataTypeFatName': "com.google.body.fat.percentage",
    'dataTypeActivitySegmentName': "com.google.activity.segment",
    'dataTypeWattsName': "com.google.power.sample",
    'OAUTH_SCOPES': 'https://www.googleapis.com/auth/fitness.sleep.read https://www.googleapis.com/auth/fitness.heart_rate.read https://www.googleapis.com/auth/fitness.reproductive_health.read https://www.googleapis.com/auth/fitness.body_temperature.read https://www.googleapis.com/auth/fitness.oxygen_saturation.read https://www.googleapis.com/auth/fitness.blood_glucose.read https://www.googleapis.com/auth/fitness.blood_pressure.read https://www.googleapis.com/auth/fitness.nutrition.read https://www.googleapis.com/auth/fitness.body.read https://www.googleapis.com/auth/fitness.location.read https://www.googleapis.com/auth/fitness.activity.read https://www.googleapis.com/auth/userinfo.profile',
    'timedelta_session': 0,
}



sentry_sdk.init(
    dsn="https://16d176ee83c64a0f903c7a413e4cc2b8@o1038060.ingest.sentry.io/6006251",
    integrations=[DjangoIntegration()],

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0,

    # If you wish to associate users to errors (assuming you are using
    # django.contrib.auth) you may enable sending PII data.
    send_default_pii=True
)
