# Generated by Django 3.2.6 on 2021-09-13 14:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('1', 'Anaeróbico'), ('2', 'Aeróbico')], default='1', max_length=1)),
                ('zona', models.CharField(choices=[('1', 'Superior'), ('2', 'Tren inferior'), ('3', 'Full body')], default='2', max_length=1)),
                ('reps', models.CharField(blank=True, default='', max_length=20)),
                ('tiempo', models.CharField(blank=True, default='', help_text='Tiempo en segundos', max_length=20)),
                ('imagen', models.ImageField(blank=True, default='', upload_to='img/', verbose_name='Imagen')),
                ('url', models.CharField(blank=True, default='', help_text='Url de vídeo', max_length=120, verbose_name='Vídeo')),
                ('nivel', models.CharField(choices=[('1', 'Inicial'), ('2', 'Medio'), ('3', 'Avanzado')], default='1', max_length=1)),
                ('indicaciones', models.CharField(blank=True, default='', max_length=255)),
                ('orden', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anyo', models.IntegerField(default='2021', verbose_name='Año')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto')], default=9, verbose_name='Mes')),
                ('peso', models.FloatField(default=30.0)),
                ('imc', models.FloatField(blank=True, default=0.0)),
                ('grasa', models.FloatField(blank=True, default=0.0)),
                ('musculo', models.FloatField(blank=True, default=0.0)),
                ('cintura', models.FloatField(blank=True, default=0.0)),
                ('pecho', models.FloatField(blank=True, default=0.0)),
                ('biceps', models.FloatField(blank=True, default=0.0)),
                ('muslo', models.FloatField(blank=True, default=0.0)),
                ('gemelo', models.FloatField(blank=True, default=0.0)),
                ('caliper', models.FloatField(blank=True, default=0.0)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('series', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('comentario', models.CharField(blank=True, default='', max_length=300)),
                ('completado', models.IntegerField(choices=[(0, 'NO REALIZADO'), (1, 'COMPLETO'), (2, 'SEMICOMPLETO')], default=0)),
                ('activo', models.BooleanField(default=True)),
                ('ejercicios', models.ManyToManyField(to='fitapp.Ejercicio')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
