# Generated by Django 3.2.6 on 2021-10-03 22:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitapp', '0004_alter_medida_mes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medida',
            unique_together={('mes', 'anyo', 'user')},
        ),
    ]
