# Generated by Django 3.2.6 on 2021-10-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0005_alter_medida_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='calorias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='distancia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='pasos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
