# Generated by Django 3.2.6 on 2021-10-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0007_auto_20211005_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
