# Generated by Django 3.2.6 on 2021-10-07 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0010_sesionesgoogle_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesionesgoogle',
            old_name='activity',
            new_name='activityType',
        ),
        migrations.RenameField(
            model_name='sesionesgoogle',
            old_name='endTimeMillis',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='sesionesgoogle',
            old_name='startTimeMillis',
            new_name='start',
        ),
    ]
