# Generated by Django 3.2.6 on 2021-10-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0011_auto_20211007_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='heart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
