# Generated by Django 3.2.6 on 2021-10-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0012_calendario_heart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionesgoogle',
            name='duration',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
