# Generated by Django 3.2.6 on 2021-10-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0013_sesionesgoogle_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionesgoogle',
            name='activityType',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sesionesgoogle',
            name='end',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sesionesgoogle',
            name='start',
            field=models.IntegerField(max_length=200),
        ),
    ]
