# Generated by Django 3.2.6 on 2021-10-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0014_auto_20211009_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionesgoogle',
            name='end',
            field=models.BigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sesionesgoogle',
            name='start',
            field=models.BigIntegerField(),
        ),
    ]
