# Generated by Django 3.2.6 on 2021-10-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0015_auto_20211009_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='session_google',
        ),
        migrations.AddField(
            model_name='calendario',
            name='session_google',
            field=models.ManyToManyField(to='fitapp.SesionesGoogle'),
        ),
        migrations.AlterField(
            model_name='sesionesgoogle',
            name='end',
            field=models.BigIntegerField(),
        ),
    ]
