# Generated by Django 3.2.6 on 2021-10-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0017_alter_sesionesgoogle_id_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionesgoogle',
            name='id_google',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
