# Generated by Django 3.2.6 on 2021-10-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0019_alter_sesionesgoogle_id_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionesgoogle',
            name='id_google',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
