# Generated by Django 3.2.6 on 2021-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0021_auto_20211013_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='instagram_code',
            field=models.CharField(blank=True, default='', help_text='Código Instagram', max_length=320, verbose_name='Vídeo'),
        ),
    ]
