# Generated by Django 3.2.6 on 2021-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0022_ejercicio_instagram_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='instagram_code',
            field=models.CharField(blank=True, default='', help_text='Código Instagram', max_length=520, verbose_name='Vídeo'),
        ),
    ]
