# Generated by Django 3.2.6 on 2021-10-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0024_alter_ejercicio_instagram_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='instagram_code',
            field=models.TextField(blank=True, default='', help_text='Código Instagram', max_length=720, verbose_name='Vídeo'),
        ),
    ]
